name: CalVer Tagging
on:
  workflow_dispatch:
    inputs:
      variant:
        required: true
        description: Variant tag to pass to CalVer
        type: string
  push:
    branches:
      - "**"
    tags:
      - "!**"
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  apply:
    runs-on: ${{ vars.PREFERRED_RUNNER || 'ubuntu-latest' }}
    name: Tag revision
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version
        uses: acrois/calver@trunk
